name: Build and Configure AMI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        sudo apt-get install -y ansible
        sudo apt-get install -y awscli
        sudo apt-get install -y make

    - name: Build AMI with Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip
        unzip packer_1.7.0_linux_amd64.zip
        sudo mv packer /usr/local/bin/
        packer build packer.json

    - name: Configure AMI with Ansible
      run: |
        ansible-playbook -i inventory configure.yml
